### ISSUE TITLE
error when import gnewsclient

### ISSUE THREAD

**Issue by b0yasyik** [nikhilkumarsingh/gnewsclient#20]
i have an error when try import gnewsclient

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\gnewsclient\__init__.py", line 1, in <modu
le>
    from .gnewsclient import gnewsclient
  File "C:\Python27\lib\site-packages\gnewsclient\gnewsclient.py", line 3, in <m
odule>
    from bs4 import BeautifulSoup
  File "C:\Python27\lib\site-packages\bs4\__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "C:\Python27\lib\site-packages\bs4\builder\__init__.py", line 311, in <mo
dule>
    from . import _html5lib
  File "C:\Python27\lib\site-packages\bs4\builder\_html5lib.py", line 57, in <mo
dule>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

my os windows 7 with python 2.7
i am install gnewsclient with pip
sorry for my bad english

**Comment by nikhilkumarsingh** [comment]
There seems to be some issue with `html5lib`. Try:
```
pip install --upgrade html5lib==1.0b8
```

For more solutions, see [this](https://stackoverflow.com/questions/38447738/beautifulsoup-html5lib-module-object-has-no-attribute-base)

**Comment by b0yasyik** [comment]
finally work thanks ... :)
